# This is adapted from Atari configuration 
NAME_INITIALS: "RE"
ALG_NAME: "pqn"
TOTAL_TIMESTEPS: 5e7 # 1e8 == 100M, but times 4 (frame-skipping) -> pqn paper: enough to outperform Rainbow
TOTAL_TIMESTEPS_DECAY: 5e7 # will be used for decay functions, in case you want to test for less timesteps and keep decays same
NUM_ENVS: 1024 # parallel environments
NUM_STEPS: 16 # steps per environment in each update
# NUM_ENVS / NUM_STEPS should be 8 for original PQN (they did 128/32) -> increasing number of updates here by decreasing NUM_STEPS
EPS_START: 1.0
EPS_FINISH: 0.01
EPS_DECAY: 0.2
NUM_EPOCHS: 3 
NUM_MINIBATCHES: 16 # minibatches per epoch
NORM_TYPE: "layer_norm" # layer_norm or batch_norm
LR: 5e-4
MAX_GRAD_NORM: 1
LR_LINEAR_DECAY: True
GAMMA: 0.99
LAMBDA: 0.65

# env specific
ENV_NAME: "asterix"
ENV_KWARGS: {}
OBJECT_CENTRIC: True
PIXEL_GRAYSCALE: True
PIXEL_RESIZE: True
PIXEL_RESIZE_SHAPE: [84, 84]
USE_NATIVE_DOWNSCALING: True
# Apply this mod during testing
# Activate this only for the test run (or debugging)
# Set to None for final training run.
#MOD_NAME: LazyEnemyWrapper

# Note: This will massively increase compile and run time!
# Turn off for final reported training run.
TEST_DURING_TRAINING: False
TEST_INTERVAL: 0.01 # in terms of total updates
TEST_NUM_ENVS: 128
TEST_NUM_STEPS: 10000
EPS_TEST: 0.0 # 0 for greedy policy
RECORD_VIDEO: True 